### ISSUE TITLE
Problem in data preprocessing

### ISSUE THREAD

**Issue by lance11320** [EBGU/RodentTracker#1]
Hi Yinjun,

Your work on self-supervised features extraction is amazing! However, here is still a few problems when I try to set Selfee up on a online platform (as RTX3090 is still not that accessible for our traditional biology lab).

The first problem is in the "data preprocessing" step. I tried to use your rodenttracker to extract frames and remove background. I modified the Supertracker_OFT_Template script as suggested (I don't know if I have modified the correct script):

![1656914687063](https://user-images.githubusercontent.com/55554657/177094831-36a41249-cea3-47de-b7c6-2a44a6d32ff2.png)

When running it in terminal, it returns a error like this:

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I search the internet for it and find some say it is because the path is relative path but not absolute path. But there seems to be no relative path pass to any functions. Could you please give some more detailed instructions to me on this problem? Many thanks! Hoping to hear from you soon.

**Comment by EBGU** [comment]
Thank you for using our software!
First, what kind of online platform you are using? Image preprocessing and inference of Selfee do not require an RTX3090 GPU, you can do it on any computer. This script has a GUI, so using terminals to connect to a remote server may not work.
Second, could you paste the complete error message showing which row causes the error?
Last, you might need to check the access of your source data.

**Comment by lance11320** [comment]
![image](https://user-images.githubusercontent.com/55554657/177108083-76a87f28-08b7-47a6-92df-c693fae7c3c7.png)
Thank you for your fast reply! Here is the feedback in the terminal. 
I used 'Featurize' and used terminal to remote connect to server.  
There is some problem with the GUI before, so, I set the 'preview' as False, and comment some code including "imshow" out, I guess this could still not solve all the problems.

**Comment by EBGU** [comment]
From the error message, your program saved some cache in the video folder which caused the error. Also, the GUI is required and you can't just comment those imshow codes. You need the GUI to select ROI for preprocessing. Please see the header of these scripts:


For EPM, please select pionts from the OPEN arm to the CLOSE arm and press y:
          o1
       c3    c4
          o2
For OFT, please select pionts clockwise from upper left corner and press y:
      UL1  UR2
      LL4  LR3
Press y to confirm remove background.
For EPM please select the central neutral zone(four points, like OFT) and press y to confirm.

**Comment by lance11320** [comment]
Thanks for your kind instruction! I see!
